### PR TITLE
Refactor code in smaller files and remove most IDE warnings

### PR DESCRIPTION
**Pull request by pohlm01**
I hope this doesn't take you too much by surprise. Let me know if you don't agree with (parts of) it.
I made an attempt to bring a bit more structure into the code and especially split up the very long `mtc.go` file into multiple. For now, I stored most stuff in the `/pkg` directory, but I would leave it up to you, if you prefer it in the `/internal` folder (for now).

The changes should not contain any functional changes.

### CODE REVIEW

**Comment by bwesterb** [comment]
I strongly prefer to keep code together in one file that's closely related, and instead split on what could've been a separate package. It makes it easier to jump back and forth between related definitions. Also, it reduces time spent thinking about what file to put new code in. At some point this becomes unwieldy, but that'd be if the file grows above say 3000 lines of code or so.

**Comment by pohlm01** [comment]
Fine, no problem. I'll close this PR then.

**Comment by bwesterb** [comment]
Btw, your IDE uses golanglint-cli?

**Comment by pohlm01** [comment]
As far as I know, it does not. I'm using the default settings of GoLand from JetBrains.

**Comment by bwesterb** [comment]
I fixed some issues raised by golangci-lint in https://github.com/bwesterb/mtc/commit/76c878237ac7f4a1347e824d03948f51cab2939d. I'll enable it in CI once all are fixed.

**Pull request closed without merging**
